export enum PromocodesErrorCode {
  PROMOCODE_NOT_FOUND = 'PROMOCODE_NOT_FOUND',
  PROMOCODE_CODE_TAKEN = 'PROMOCODE_CODE_TAKEN',
  PROMOCODE_EXPIRED = 'PROMOCODE_EXPIRED',
  ACTIVATION_LIMIT_REACHED = 'ACTIVATION_LIMIT_REACHED',
  ACTIVATION_DUPLICATE = 'ACTIVATION_DUPLICATE',
}
